"""Add Users table

Revision ID: de098a1c7f3a
Revises: 33df2fc829c5
Create Date: 2020-10-08 15:57:01.060817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "de098a1c7f3a"
down_revision = "33df2fc829c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=150), nullable=True),
        sa.Column("api_key", sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("tweets", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "tweets", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tweets", type_="foreignkey")
    op.drop_column("tweets", "user_id")
    op.drop_table("users")
    # ### end Alembic commands ###
